# Generated by Django 6.0 on 2025-12-14 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiremodel',
            name='talent_contact',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='hiremodel',
            name='talent_location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
